package EventDrivenProgramming;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 * A frame that illustrates the use of checkboxes
 *
 */
public class RadioButtonFrame extends JFrame implements ActionListener, ItemListener {
	ButtonGroup group;
	Container contentPane;
	JCheckBox automobilesCB, planesCB, trainsCB;
	JLabel titleLabel;
	JTextArea textArea;

	/**
	 * Default constructor
	 */
	public RadioButtonFrame() {
		JPanel south;

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		contentPane = getContentPane();

		contentPane.setLayout(new BorderLayout());

		titleLabel = new JLabel();
		titleLabel.setText("A RadioButton Example");
		contentPane.add(titleLabel, BorderLayout.NORTH);

		textArea = new JTextArea(40, 20);
		contentPane.add(textArea, BorderLayout.CENTER);

		south = new JPanel();
		south.setLayout(new FlowLayout());
		contentPane.add(south, BorderLayout.SOUTH);

		planesCB = new JCheckBox("Planes");
		planesCB.setActionCommand("planesCB");
		planesCB.setMnemonic('P');
		planesCB.addItemListener(this);
		south.add(planesCB, BorderLayout.WEST);

		trainsCB = new JCheckBox("Trains");
		trainsCB.setActionCommand("trainsCB");
		trainsCB.setMnemonic('T');
		trainsCB.addItemListener(this);
		south.add(trainsCB, BorderLayout.EAST);

		automobilesCB = new JCheckBox("Automobiles");
		automobilesCB.setActionCommand("automobilesCB");
		automobilesCB.setMnemonic('A');
		automobilesCB.addItemListener(this);
		south.add(automobilesCB, BorderLayout.SOUTH);

		// This is different
		group = new ButtonGroup();
		group.add(planesCB);
		group.add(trainsCB);
		group.add(automobilesCB);
	}

	/**
	 * Handle actionPerformed events (required by ActionListener)
	 *
	 * @param e
	 *            The event
	 */
	public void actionPerformed(ActionEvent e) {
		// You could handle events generated by the
		// JCheckBox objects here
	}

	/**
	 * Handle itemStateChanged events (required by ItemListener)
	 *
	 * @param e
	 *            The event
	 */
	public void itemStateChanged(ItemEvent e) {
		int state;
		JToggleButton tb;

		tb = (JToggleButton) (e.getItem());
		state = e.getStateChange();

		if (tb.getActionCommand().equals("planesCB")) {
			if (state == ItemEvent.SELECTED) {
				textArea.append("If you were meant to fly " + "you'd have wings\n\n");
			} else if (state == ItemEvent.DESELECTED) {
				textArea.append("Afraid to fly???\n\n");
			}
		} else if (tb.getActionCommand().equals("trainsCB")) {
			if (state == ItemEvent.SELECTED) {
				textArea.append("Choo, Choo...\n\n");
			} else if (state == ItemEvent.DESELECTED) {
				textArea.append("The little engine that couldn't!\n\n");
			}
		} else if (tb.getActionCommand().equals("automobilesCB")) {
			if (state == ItemEvent.SELECTED) {
				textArea.append("I drove a Geo Prizm in 1995!\n\n");
			} else if (state == ItemEvent.DESELECTED) {
				textArea.append("I drive the same one today!\n\n");
			}
		}
	}
}
