# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/myand.v/myand.v.cache/wt [current_project]
set_property parent.project_path T:/myand.v/myand.v.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo t:/myand.v/myand.v.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib T:/myand.v/myand.v.srcs/sources_1/new/myand.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc T:/myand.v/myand.v.srcs/constrs_1/new/myinv_pin.xdc
set_property used_in_implementation false [get_files T:/myand.v/myand.v.srcs/constrs_1/new/myinv_pin.xdc]


synth_design -top myand -part xc7a100tcsg324-1


write_checkpoint -force -noxdef myand.dcp

catch { report_utilization -file myand_utilization_synth.rpt -pb myand_utilization_synth.pb }
